### ISSUE TITLE
Capital letters in device_id fail login

### ISSUE THREAD

**Issue by daviddever** [linuxwhatelse/plugin.audio.linuxwhatelse.gmusic#17]
Minor bug that I noticed, but when configuring the device_id through the setup, initially I pasted the string from my phone using the Yatze remote, but the authentication failed.

Unfortunately, I didn't save the log but it showed the error had my value for device_id, with the capitals, and then gave me a list of what looked like possible valid id's which I noticed one was the same but just without the capitals so I tried again entering the string in lowercase.

I think (but obviously could be wrong) it might be a simple fix to use .lower on the device_id string here: [https://github.com/linuxwhatelse/plugin.audio.linuxwhatelse.gmusic/blob/master/addon/gmusic_wrapper.py#L63](url)

Might save someone else some confusion. Thanks for all your work on this plugin.

**Comment by tadly** [comment]
Hi and thanks for taking the time for reporting.
I just did a clean test and even mixed upper- and lowercase letters within the same device-id and had no problems logging in.

Sure you haven't had a typo or something?
(Logging sadly isn't the strong-point of my addon)

**Comment by daviddever** [comment]
Sorry about that then, I must have accidentally been pasting a space or some other character that caused the failure. Thanks for taking a look.

**Comment by tadly** [comment]
Sure thing, no problem.
