### ISSUE TITLE
Sync/Import library at a defined interval

### ISSUE THREAD

**Issue by da-anda** [linuxwhatelse/plugin.audio.linuxwhatelse.gmusic#7]
It would be great if the library could be synced in defined intervals, like "every day", "weekly", ...

**Comment by tadly** [comment]
Added with 5d615d4c6a709c6c6985004eb7044436ee07546b and will be in the next release.

I decided to go with the "choose an hour-based value"-approach as it allows for pretty much everything a user could want.
Yes, "every day", "weekly" would be more user-friendly but I hear people already whining about a certain value missing.

This approach was easy to implement and as long as the user can to basic math he will be fine :)
